/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package programa;

import javax.swing.JOptionPane;

/**
 *
 * @author Equip
 */
public class frmMenus extends javax.swing.JFrame {

    /**
     * Creates new form frmMenus
     */
    public frmMenus() {
        initComponents();
        this.setLocationRelativeTo(this);   //situado al centro
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        menucontextual = new javax.swing.JPopupMenu();
        mnuApagarT1 = new javax.swing.JMenuItem();
        mnuEncenderT1 = new javax.swing.JMenuItem();
        jSeparator9 = new javax.swing.JPopupMenu.Separator();
        mnuTodasD1 = new javax.swing.JMenuItem();
        mnuTodasN1 = new javax.swing.JMenuItem();
        jSeparator10 = new javax.swing.JPopupMenu.Separator();
        mnuPrincipales1 = new javax.swing.JMenuItem();
        mnuSecudarias1 = new javax.swing.JMenuItem();
        mnuSeguridad1 = new javax.swing.JMenuItem();
        pnOficina1 = new javax.swing.JPanel();
        chkLuzPrincipal1 = new javax.swing.JCheckBox();
        chkLuzSecundaria1 = new javax.swing.JCheckBox();
        chkLuzSeguridad1 = new javax.swing.JCheckBox();
        pnOficina2 = new javax.swing.JPanel();
        chkLuzPrincipal2 = new javax.swing.JCheckBox();
        chkLuzSecundaria2 = new javax.swing.JCheckBox();
        chkLuzSeguridad2 = new javax.swing.JCheckBox();
        pnOficina3 = new javax.swing.JPanel();
        chkLuzPrincipal3 = new javax.swing.JCheckBox();
        chkLuzSecundaria3 = new javax.swing.JCheckBox();
        chkLuzSeguridad3 = new javax.swing.JCheckBox();
        jToolBar1 = new javax.swing.JToolBar();
        bapagartodas = new javax.swing.JButton();
        bencendertodas = new javax.swing.JButton();
        jSeparator6 = new javax.swing.JToolBar.Separator();
        bdia = new javax.swing.JButton();
        bnoche = new javax.swing.JButton();
        bdiaicono = new javax.swing.JButton();
        bnocheicono = new javax.swing.JButton();
        jSeparator7 = new javax.swing.JToolBar.Separator();
        binfoprincipales = new javax.swing.JButton();
        binfosecundarias = new javax.swing.JButton();
        binfoseguridad = new javax.swing.JButton();
        jSeparator8 = new javax.swing.JToolBar.Separator();
        mnuBarraMenus = new javax.swing.JMenuBar();
        mnuActivación = new javax.swing.JMenu();
        mnuApagarT = new javax.swing.JMenuItem();
        mnuEncenderT = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        mnuDia = new javax.swing.JMenu();
        mnuOfD1 = new javax.swing.JMenuItem();
        mnuOfD2 = new javax.swing.JMenuItem();
        mnuOfD3 = new javax.swing.JMenuItem();
        jSeparator3 = new javax.swing.JPopupMenu.Separator();
        mnuTodasD = new javax.swing.JMenuItem();
        mnuNoche = new javax.swing.JMenu();
        mnuOfN1 = new javax.swing.JMenuItem();
        mnuOfN2 = new javax.swing.JMenuItem();
        mnuOfN3 = new javax.swing.JMenuItem();
        jSeparator4 = new javax.swing.JPopupMenu.Separator();
        mnuTodasN = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        mnuSalir = new javax.swing.JMenuItem();
        mnuInfo = new javax.swing.JMenu();
        mnuPrincipales = new javax.swing.JMenuItem();
        mnuSecudarias = new javax.swing.JMenuItem();
        mnuSeguridad = new javax.swing.JMenuItem();
        jSeparator5 = new javax.swing.JPopupMenu.Separator();
        mnuAcerca = new javax.swing.JMenuItem();

        menucontextual.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menucontextualMouseClicked(evt);
            }
        });

        mnuApagarT1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, java.awt.event.InputEvent.CTRL_MASK));
        mnuApagarT1.setText("Apagar Todas");
        mnuApagarT1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuApagarT1ActionPerformed(evt);
            }
        });
        menucontextual.add(mnuApagarT1);

        mnuEncenderT1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_E, java.awt.event.InputEvent.CTRL_MASK));
        mnuEncenderT1.setText("Encender Todas");
        mnuEncenderT1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuEncenderT1ActionPerformed(evt);
            }
        });
        menucontextual.add(mnuEncenderT1);
        menucontextual.add(jSeparator9);

        mnuTodasD1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_D, java.awt.event.InputEvent.CTRL_MASK));
        mnuTodasD1.setText("Modo Dia");
        mnuTodasD1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuTodasD1ActionPerformed(evt);
            }
        });
        menucontextual.add(mnuTodasD1);

        mnuTodasN1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_N, java.awt.event.InputEvent.CTRL_MASK));
        mnuTodasN1.setText("Modo Noche");
        mnuTodasN1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuTodasN1ActionPerformed(evt);
            }
        });
        menucontextual.add(mnuTodasN1);
        menucontextual.add(jSeparator10);

        mnuPrincipales1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_P, java.awt.event.InputEvent.CTRL_MASK));
        mnuPrincipales1.setText("Principales");
        mnuPrincipales1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuPrincipales1ActionPerformed(evt);
            }
        });
        menucontextual.add(mnuPrincipales1);

        mnuSecudarias1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.CTRL_MASK));
        mnuSecudarias1.setText("Secundarias");
        mnuSecudarias1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuSecudarias1ActionPerformed(evt);
            }
        });
        menucontextual.add(mnuSecudarias1);

        mnuSeguridad1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_G, java.awt.event.InputEvent.CTRL_MASK));
        mnuSeguridad1.setText("Seguridad");
        mnuSeguridad1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuSeguridad1ActionPerformed(evt);
            }
        });
        menucontextual.add(mnuSeguridad1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                formMouseClicked(evt);
            }
        });

        pnOficina1.setBackground(new java.awt.Color(153, 255, 255));
        pnOficina1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Oficina 1", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(0, 51, 51))); // NOI18N

        chkLuzPrincipal1.setText("Luz Principal");

        chkLuzSecundaria1.setText("Luz Secundarial");

        chkLuzSeguridad1.setText("Luz Seguridadl");

        javax.swing.GroupLayout pnOficina1Layout = new javax.swing.GroupLayout(pnOficina1);
        pnOficina1.setLayout(pnOficina1Layout);
        pnOficina1Layout.setHorizontalGroup(
            pnOficina1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnOficina1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnOficina1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(chkLuzPrincipal1)
                    .addComponent(chkLuzSecundaria1)
                    .addComponent(chkLuzSeguridad1))
                .addContainerGap(82, Short.MAX_VALUE))
        );
        pnOficina1Layout.setVerticalGroup(
            pnOficina1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnOficina1Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(chkLuzPrincipal1)
                .addGap(24, 24, 24)
                .addComponent(chkLuzSecundaria1)
                .addGap(24, 24, 24)
                .addComponent(chkLuzSeguridad1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pnOficina2.setBackground(new java.awt.Color(255, 255, 204));
        pnOficina2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Oficina 2", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(51, 51, 0))); // NOI18N

        chkLuzPrincipal2.setText("Luz Principal");

        chkLuzSecundaria2.setText("Luz Secundarial");

        chkLuzSeguridad2.setText("Luz Seguridadl");

        javax.swing.GroupLayout pnOficina2Layout = new javax.swing.GroupLayout(pnOficina2);
        pnOficina2.setLayout(pnOficina2Layout);
        pnOficina2Layout.setHorizontalGroup(
            pnOficina2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnOficina2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnOficina2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(chkLuzPrincipal2)
                    .addComponent(chkLuzSecundaria2)
                    .addComponent(chkLuzSeguridad2))
                .addContainerGap(82, Short.MAX_VALUE))
        );
        pnOficina2Layout.setVerticalGroup(
            pnOficina2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnOficina2Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(chkLuzPrincipal2)
                .addGap(24, 24, 24)
                .addComponent(chkLuzSecundaria2)
                .addGap(24, 24, 24)
                .addComponent(chkLuzSeguridad2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pnOficina3.setBackground(new java.awt.Color(204, 255, 204));
        pnOficina3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Oficina 3", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(0, 51, 51))); // NOI18N

        chkLuzPrincipal3.setText("Luz Principal");

        chkLuzSecundaria3.setText("Luz Secundarial");

        chkLuzSeguridad3.setText("Luz Seguridadl");

        javax.swing.GroupLayout pnOficina3Layout = new javax.swing.GroupLayout(pnOficina3);
        pnOficina3.setLayout(pnOficina3Layout);
        pnOficina3Layout.setHorizontalGroup(
            pnOficina3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnOficina3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnOficina3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(chkLuzPrincipal3)
                    .addComponent(chkLuzSecundaria3)
                    .addComponent(chkLuzSeguridad3))
                .addContainerGap(82, Short.MAX_VALUE))
        );
        pnOficina3Layout.setVerticalGroup(
            pnOficina3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnOficina3Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(chkLuzPrincipal3)
                .addGap(24, 24, 24)
                .addComponent(chkLuzSecundaria3)
                .addGap(24, 24, 24)
                .addComponent(chkLuzSeguridad3)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jToolBar1.setRollover(true);

        bapagartodas.setText("apagar todas");
        bapagartodas.setFocusable(false);
        bapagartodas.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        bapagartodas.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        bapagartodas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bapagartodasActionPerformed(evt);
            }
        });
        jToolBar1.add(bapagartodas);

        bencendertodas.setText("encender todas");
        bencendertodas.setFocusable(false);
        bencendertodas.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        bencendertodas.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        bencendertodas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bencendertodasActionPerformed(evt);
            }
        });
        jToolBar1.add(bencendertodas);
        jToolBar1.add(jSeparator6);

        bdia.setText("DIA");
        bdia.setFocusable(false);
        bdia.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        bdia.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        bdia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bdiaActionPerformed(evt);
            }
        });
        jToolBar1.add(bdia);

        bnoche.setText("NOCHE");
        bnoche.setFocusable(false);
        bnoche.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        bnoche.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        bnoche.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bnocheActionPerformed(evt);
            }
        });
        jToolBar1.add(bnoche);

        bdiaicono.setIcon(new javax.swing.ImageIcon("C:\\Users\\alexis\\Documents\\NetBeansProjects\\MenuBHPop1415\\src\\programa\\iconos\\dia.png")); // NOI18N
        bdiaicono.setFocusable(false);
        bdiaicono.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        bdiaicono.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        bdiaicono.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bdiaiconoActionPerformed(evt);
            }
        });
        jToolBar1.add(bdiaicono);

        bnocheicono.setIcon(new javax.swing.ImageIcon("C:\\Users\\alexis\\Documents\\NetBeansProjects\\MenuBHPop1415\\src\\programa\\iconos\\luna.png")); // NOI18N
        bnocheicono.setFocusable(false);
        bnocheicono.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        bnocheicono.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        bnocheicono.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bnocheiconoActionPerformed(evt);
            }
        });
        jToolBar1.add(bnocheicono);
        jToolBar1.add(jSeparator7);

        binfoprincipales.setText("info Principales");
        binfoprincipales.setFocusable(false);
        binfoprincipales.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        binfoprincipales.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        binfoprincipales.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                binfoprincipalesActionPerformed(evt);
            }
        });
        jToolBar1.add(binfoprincipales);

        binfosecundarias.setText("info Secundarias");
        binfosecundarias.setFocusable(false);
        binfosecundarias.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        binfosecundarias.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        binfosecundarias.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                binfosecundariasActionPerformed(evt);
            }
        });
        jToolBar1.add(binfosecundarias);

        binfoseguridad.setText("info Seguridad");
        binfoseguridad.setFocusable(false);
        binfoseguridad.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        binfoseguridad.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        binfoseguridad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                binfoseguridadActionPerformed(evt);
            }
        });
        jToolBar1.add(binfoseguridad);
        jToolBar1.add(jSeparator8);

        mnuActivación.setText("Activación");

        mnuApagarT.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, java.awt.event.InputEvent.CTRL_MASK));
        mnuApagarT.setText("Apagar Todas");
        mnuApagarT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuApagarTActionPerformed(evt);
            }
        });
        mnuActivación.add(mnuApagarT);

        mnuEncenderT.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_E, java.awt.event.InputEvent.CTRL_MASK));
        mnuEncenderT.setText("Encender Todas");
        mnuEncenderT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuEncenderTActionPerformed(evt);
            }
        });
        mnuActivación.add(mnuEncenderT);
        mnuActivación.add(jSeparator1);

        mnuDia.setText("Dia");

        mnuOfD1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_1, java.awt.event.InputEvent.CTRL_MASK));
        mnuOfD1.setText("Oficina 1");
        mnuOfD1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuOfD1ActionPerformed(evt);
            }
        });
        mnuDia.add(mnuOfD1);

        mnuOfD2.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_2, java.awt.event.InputEvent.CTRL_MASK));
        mnuOfD2.setText("Oficina 2");
        mnuOfD2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuOfD2ActionPerformed(evt);
            }
        });
        mnuDia.add(mnuOfD2);

        mnuOfD3.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_3, java.awt.event.InputEvent.CTRL_MASK));
        mnuOfD3.setText("Oficina 3");
        mnuOfD3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuOfD3ActionPerformed(evt);
            }
        });
        mnuDia.add(mnuOfD3);
        mnuDia.add(jSeparator3);

        mnuTodasD.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_D, java.awt.event.InputEvent.CTRL_MASK));
        mnuTodasD.setText("Todas");
        mnuTodasD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuTodasDActionPerformed(evt);
            }
        });
        mnuDia.add(mnuTodasD);

        mnuActivación.add(mnuDia);

        mnuNoche.setText("Noche");

        mnuOfN1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_4, java.awt.event.InputEvent.CTRL_MASK));
        mnuOfN1.setText("Oficina 1");
        mnuOfN1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuOfN1ActionPerformed(evt);
            }
        });
        mnuNoche.add(mnuOfN1);

        mnuOfN2.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_5, java.awt.event.InputEvent.CTRL_MASK));
        mnuOfN2.setText("Oficina 2");
        mnuOfN2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuOfN2ActionPerformed(evt);
            }
        });
        mnuNoche.add(mnuOfN2);

        mnuOfN3.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_6, java.awt.event.InputEvent.CTRL_MASK));
        mnuOfN3.setText("Oficina 3");
        mnuOfN3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuOfN3ActionPerformed(evt);
            }
        });
        mnuNoche.add(mnuOfN3);
        mnuNoche.add(jSeparator4);

        mnuTodasN.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_N, java.awt.event.InputEvent.CTRL_MASK));
        mnuTodasN.setText("Todas");
        mnuTodasN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuTodasNActionPerformed(evt);
            }
        });
        mnuNoche.add(mnuTodasN);

        mnuActivación.add(mnuNoche);
        mnuActivación.add(jSeparator2);

        mnuSalir.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_X, java.awt.event.InputEvent.CTRL_MASK));
        mnuSalir.setText("Salir");
        mnuSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuSalirActionPerformed(evt);
            }
        });
        mnuActivación.add(mnuSalir);

        mnuBarraMenus.add(mnuActivación);

        mnuInfo.setText("Info");

        mnuPrincipales.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_P, java.awt.event.InputEvent.CTRL_MASK));
        mnuPrincipales.setText("Principales");
        mnuPrincipales.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuPrincipalesActionPerformed(evt);
            }
        });
        mnuInfo.add(mnuPrincipales);

        mnuSecudarias.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.CTRL_MASK));
        mnuSecudarias.setText("Secundarias");
        mnuSecudarias.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuSecudariasActionPerformed(evt);
            }
        });
        mnuInfo.add(mnuSecudarias);

        mnuSeguridad.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_G, java.awt.event.InputEvent.CTRL_MASK));
        mnuSeguridad.setText("Seguridad");
        mnuSeguridad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuSeguridadActionPerformed(evt);
            }
        });
        mnuInfo.add(mnuSeguridad);
        mnuInfo.add(jSeparator5);

        mnuAcerca.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_H, java.awt.event.InputEvent.CTRL_MASK));
        mnuAcerca.setText("Acerca de...");
        mnuInfo.add(mnuAcerca);

        mnuBarraMenus.add(mnuInfo);

        setJMenuBar(mnuBarraMenus);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jToolBar1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(pnOficina1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(pnOficina2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(pnOficina3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(68, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(120, 120, 120)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnOficina3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pnOficina2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pnOficina1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(167, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mnuOfD1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuOfD1ActionPerformed
        chkLuzPrincipal1.setSelected(true);
        chkLuzSecundaria1.setSelected(true);
        chkLuzSeguridad1.setSelected(false);
    }//GEN-LAST:event_mnuOfD1ActionPerformed

    private void mnuOfD2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuOfD2ActionPerformed
        chkLuzPrincipal2.setSelected(true);
        chkLuzSecundaria2.setSelected(true);
        chkLuzSeguridad2.setSelected(false);
    }//GEN-LAST:event_mnuOfD2ActionPerformed

    private void mnuOfD3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuOfD3ActionPerformed
        chkLuzPrincipal3.setSelected(true);
        chkLuzSecundaria3.setSelected(true);
        chkLuzSeguridad3.setSelected(false);
    }//GEN-LAST:event_mnuOfD3ActionPerformed

    private void mnuTodasDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuTodasDActionPerformed
        mnuOfD1ActionPerformed(null);
        mnuOfD2ActionPerformed(null);
        mnuOfD3ActionPerformed(null);
    }//GEN-LAST:event_mnuTodasDActionPerformed

    private void mnuOfN1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuOfN1ActionPerformed
        chkLuzPrincipal1.setSelected(false);
        chkLuzSecundaria1.setSelected(false);
        chkLuzSeguridad1.setSelected(true);
    }//GEN-LAST:event_mnuOfN1ActionPerformed

    private void mnuOfN2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuOfN2ActionPerformed
        chkLuzPrincipal2.setSelected(false);
        chkLuzSecundaria2.setSelected(false);
        chkLuzSeguridad2.setSelected(true);
    }//GEN-LAST:event_mnuOfN2ActionPerformed

    private void mnuOfN3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuOfN3ActionPerformed
        chkLuzPrincipal3.setSelected(false);
        chkLuzSecundaria3.setSelected(false);
        chkLuzSeguridad3.setSelected(true);
    }//GEN-LAST:event_mnuOfN3ActionPerformed

    private void mnuTodasNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuTodasNActionPerformed
        mnuOfN1ActionPerformed(null);
        mnuOfN2ActionPerformed(null);
        mnuOfN3ActionPerformed(null);
    }//GEN-LAST:event_mnuTodasNActionPerformed

    private void mnuSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuSalirActionPerformed
        dispose();
    }//GEN-LAST:event_mnuSalirActionPerformed

    private void mnuApagarTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuApagarTActionPerformed
        chkLuzPrincipal1.setSelected(false);
        chkLuzSecundaria1.setSelected(false);
        chkLuzSeguridad1.setSelected(false);
        chkLuzPrincipal2.setSelected(false);
        chkLuzSecundaria2.setSelected(false);
        chkLuzSeguridad2.setSelected(false);
        chkLuzPrincipal3.setSelected(false);
        chkLuzSecundaria3.setSelected(false);
        chkLuzSeguridad3.setSelected(false);
    }//GEN-LAST:event_mnuApagarTActionPerformed

    private void mnuEncenderTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuEncenderTActionPerformed
        chkLuzPrincipal1.setSelected(true);
        chkLuzSecundaria1.setSelected(true);
        chkLuzSeguridad1.setSelected(true);
        chkLuzPrincipal2.setSelected(true);
        chkLuzSecundaria2.setSelected(true);
        chkLuzSeguridad2.setSelected(true);
        chkLuzPrincipal3.setSelected(true);
        chkLuzSecundaria3.setSelected(true);
        chkLuzSeguridad3.setSelected(true);
    }//GEN-LAST:event_mnuEncenderTActionPerformed

    private void mnuPrincipalesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuPrincipalesActionPerformed
        int luces=0;
        if(chkLuzPrincipal1.isSelected())
            luces++;
        if(chkLuzPrincipal2.isSelected())
            luces++;
        if(chkLuzPrincipal3.isSelected())
            luces++;
        JOptionPane.showConfirmDialog(this, "Hay "+ luces+" encendidas y "+(3-luces)+" apagadas", "PRINCIPALES", 0);
    }//GEN-LAST:event_mnuPrincipalesActionPerformed

    private void mnuSecudariasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuSecudariasActionPerformed
        int luces=0;
        if(chkLuzSecundaria1.isSelected())
            luces++;
        if(chkLuzSecundaria2.isSelected())
            luces++;
        if(chkLuzSecundaria3.isSelected())
            luces++;
        JOptionPane.showConfirmDialog(this, "Hay "+ luces+" encendidas y "+(3-luces)+" apagadas", "SECUNDARIAS", 0);
    }//GEN-LAST:event_mnuSecudariasActionPerformed

    private void mnuSeguridadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuSeguridadActionPerformed
        int luces=0;
        if(chkLuzSeguridad1.isSelected())
            luces++;
        if(chkLuzSeguridad2.isSelected())
            luces++;
        if(chkLuzSeguridad3.isSelected())
            luces++;
        JOptionPane.showConfirmDialog(this, "Hay "+ luces+" encendidas y "+(3-luces)+" apagadas", "SEGURIDAD", 0);
    }//GEN-LAST:event_mnuSeguridadActionPerformed

    private void bapagartodasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bapagartodasActionPerformed
        chkLuzPrincipal1.setSelected(false); 
        chkLuzSecundaria1.setSelected(false); 
        chkLuzSeguridad1.setSelected(false); 
        chkLuzPrincipal2.setSelected(false); 
        chkLuzSecundaria2.setSelected(false); 
        chkLuzSeguridad2.setSelected(false); 
        chkLuzPrincipal3.setSelected(false); 
        chkLuzSecundaria3.setSelected(false); 
         chkLuzSeguridad3.setSelected(false);        // TODO add your handling code here:
    }//GEN-LAST:event_bapagartodasActionPerformed

    private void bencendertodasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bencendertodasActionPerformed

        chkLuzPrincipal1.setSelected(true);
        chkLuzSecundaria1.setSelected(true);
        chkLuzSeguridad1.setSelected(true);
        chkLuzPrincipal2.setSelected(true);
        chkLuzSecundaria2.setSelected(true);
        chkLuzSeguridad2.setSelected(true);
        chkLuzPrincipal3.setSelected(true);
        chkLuzSecundaria3.setSelected(true);
        chkLuzSeguridad3.setSelected(true);// TODO add your handling code here:
    }//GEN-LAST:event_bencendertodasActionPerformed

    private void bdiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bdiaActionPerformed
        mnuOfD1ActionPerformed(null);
        mnuOfD2ActionPerformed(null);
        mnuOfD3ActionPerformed(null);        // TODO add your handling code here:
    }//GEN-LAST:event_bdiaActionPerformed

    private void bnocheActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bnocheActionPerformed
        mnuOfN1ActionPerformed(null);
        mnuOfN2ActionPerformed(null);
        mnuOfN3ActionPerformed(null);
        
// TODO add your handling code here:
    }//GEN-LAST:event_bnocheActionPerformed

    private void bdiaiconoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bdiaiconoActionPerformed
        mnuOfD1ActionPerformed(null);
        mnuOfD2ActionPerformed(null);
        mnuOfD3ActionPerformed(null);
        // TODO add your handling code here:
    }//GEN-LAST:event_bdiaiconoActionPerformed

    private void bnocheiconoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bnocheiconoActionPerformed
        mnuOfN1ActionPerformed(null);
        mnuOfN2ActionPerformed(null);
        mnuOfN3ActionPerformed(null);        // TODO add your handling code here:
    }//GEN-LAST:event_bnocheiconoActionPerformed

    private void binfoprincipalesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_binfoprincipalesActionPerformed
int luces=0;
        if(chkLuzPrincipal1.isSelected())
            luces++;
        if(chkLuzPrincipal2.isSelected())
            luces++;
        if(chkLuzPrincipal3.isSelected())
            luces++;
        JOptionPane.showConfirmDialog(this, "Hay "+ luces+" encendidas y "+(3-luces)+" apagadas", "PRINCIPALES", 0);        // TODO add your handling code here:
    }//GEN-LAST:event_binfoprincipalesActionPerformed

    private void binfosecundariasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_binfosecundariasActionPerformed
int luces=0;
        if(chkLuzSecundaria1.isSelected())
            luces++;
        if(chkLuzSecundaria2.isSelected())
            luces++;
        if(chkLuzSecundaria3.isSelected())
            luces++;
        JOptionPane.showConfirmDialog(this, "Hay "+ luces+" encendidas y "+(3-luces)+" apagadas", "SECUNDARIAS", 0);        // TODO add your handling code here:
    }//GEN-LAST:event_binfosecundariasActionPerformed

    private void binfoseguridadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_binfoseguridadActionPerformed
int luces=0;
        if(chkLuzSeguridad1.isSelected())
            luces++;
        if(chkLuzSeguridad2.isSelected())
            luces++;
        if(chkLuzSeguridad3.isSelected())
            luces++;
        JOptionPane.showConfirmDialog(this, "Hay "+ luces+" encendidas y "+(3-luces)+" apagadas", "SEGURIDAD", 0);        // TODO add your handling code here:
    }//GEN-LAST:event_binfoseguridadActionPerformed

    private void mnuApagarT1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuApagarT1ActionPerformed
 chkLuzPrincipal1.setSelected(false); 
        chkLuzSecundaria1.setSelected(false); 
        chkLuzSeguridad1.setSelected(false); 
        chkLuzPrincipal2.setSelected(false); 
        chkLuzSecundaria2.setSelected(false); 
        chkLuzSeguridad2.setSelected(false); 
        chkLuzPrincipal3.setSelected(false); 
        chkLuzSecundaria3.setSelected(false); 
         chkLuzSeguridad3.setSelected(false);        // TODO add your handling code here:
// TODO add your handling code here:
    }//GEN-LAST:event_mnuApagarT1ActionPerformed

    private void mnuEncenderT1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuEncenderT1ActionPerformed
        chkLuzPrincipal1.setSelected(true);
        chkLuzSecundaria1.setSelected(true);
        chkLuzSeguridad1.setSelected(true);
        chkLuzPrincipal2.setSelected(true);
        chkLuzSecundaria2.setSelected(true);
        chkLuzSeguridad2.setSelected(true);
        chkLuzPrincipal3.setSelected(true);
        chkLuzSecundaria3.setSelected(true);
        chkLuzSeguridad3.setSelected(true);// T
// TODO add your handling code here:
    }//GEN-LAST:event_mnuEncenderT1ActionPerformed

    private void mnuPrincipales1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuPrincipales1ActionPerformed
        int luces=0;
        if(chkLuzPrincipal1.isSelected())
            luces++;
        if(chkLuzPrincipal2.isSelected())
            luces++;
        if(chkLuzPrincipal3.isSelected())
            luces++;
        JOptionPane.showConfirmDialog(this, "Hay "+ luces+" encendidas y "+(3-luces)+" apagadas", "PRINCIPALES", 0);        // TODO add your handling code here:
// TODO add your handling code here:
    }//GEN-LAST:event_mnuPrincipales1ActionPerformed

    private void mnuSeguridad1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuSeguridad1ActionPerformed
        int luces=0;
        if(chkLuzSeguridad1.isSelected())
            luces++;
        if(chkLuzSeguridad2.isSelected())
            luces++;
        if(chkLuzSeguridad3.isSelected())
            luces++;
        JOptionPane.showConfirmDialog(this, "Hay "+ luces+" encendidas y "+(3-luces)+" apagadas", "SEGURIDAD", 0);        // TODO add your handling code here:
// TODO add your handling code here:
    }//GEN-LAST:event_mnuSeguridad1ActionPerformed

    private void mnuSecudarias1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuSecudarias1ActionPerformed
                                            
int luces=0;
        if(chkLuzSecundaria1.isSelected())
            luces++;
        if(chkLuzSecundaria2.isSelected())
            luces++;
        if(chkLuzSecundaria3.isSelected())
            luces++;
        JOptionPane.showConfirmDialog(this, "Hay "+ luces+" encendidas y "+(3-luces)+" apagadas", "SECUNDARIAS", 0);        // TODO add your handling code here:
// TODO add your handling code here:
    }//GEN-LAST:event_mnuSecudarias1ActionPerformed

    private void menucontextualMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menucontextualMouseClicked

// TODO add your handling code here:
    }//GEN-LAST:event_menucontextualMouseClicked

    private void formMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseClicked

if(evt.getButton()==3){
        menucontextual.show(this, evt.getX(), evt.getY());
}// TODO add your handling code here:
    }//GEN-LAST:event_formMouseClicked

    private void mnuTodasN1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuTodasN1ActionPerformed
 mnuOfN1ActionPerformed(null);
        mnuOfN2ActionPerformed(null);
        mnuOfN3ActionPerformed(null);
                // TODO add your handling code here:
    }//GEN-LAST:event_mnuTodasN1ActionPerformed

    private void mnuTodasD1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuTodasD1ActionPerformed
        mnuOfD1ActionPerformed(null);
        mnuOfD2ActionPerformed(null);
        mnuOfD3ActionPerformed(null);           // TODO add your handling code here:
    }//GEN-LAST:event_mnuTodasD1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmMenus.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmMenus.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmMenus.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmMenus.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmMenus().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bapagartodas;
    private javax.swing.JButton bdia;
    private javax.swing.JButton bdiaicono;
    private javax.swing.JButton bencendertodas;
    private javax.swing.JButton binfoprincipales;
    private javax.swing.JButton binfosecundarias;
    private javax.swing.JButton binfoseguridad;
    private javax.swing.JButton bnoche;
    private javax.swing.JButton bnocheicono;
    private javax.swing.JCheckBox chkLuzPrincipal1;
    private javax.swing.JCheckBox chkLuzPrincipal2;
    private javax.swing.JCheckBox chkLuzPrincipal3;
    private javax.swing.JCheckBox chkLuzSecundaria1;
    private javax.swing.JCheckBox chkLuzSecundaria2;
    private javax.swing.JCheckBox chkLuzSecundaria3;
    private javax.swing.JCheckBox chkLuzSeguridad1;
    private javax.swing.JCheckBox chkLuzSeguridad2;
    private javax.swing.JCheckBox chkLuzSeguridad3;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JPopupMenu.Separator jSeparator10;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    private javax.swing.JPopupMenu.Separator jSeparator3;
    private javax.swing.JPopupMenu.Separator jSeparator4;
    private javax.swing.JPopupMenu.Separator jSeparator5;
    private javax.swing.JToolBar.Separator jSeparator6;
    private javax.swing.JToolBar.Separator jSeparator7;
    private javax.swing.JToolBar.Separator jSeparator8;
    private javax.swing.JPopupMenu.Separator jSeparator9;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JPopupMenu menucontextual;
    private javax.swing.JMenuItem mnuAcerca;
    private javax.swing.JMenu mnuActivación;
    private javax.swing.JMenuItem mnuApagarT;
    private javax.swing.JMenuItem mnuApagarT1;
    private javax.swing.JMenuBar mnuBarraMenus;
    private javax.swing.JMenu mnuDia;
    private javax.swing.JMenuItem mnuEncenderT;
    private javax.swing.JMenuItem mnuEncenderT1;
    private javax.swing.JMenu mnuInfo;
    private javax.swing.JMenu mnuNoche;
    private javax.swing.JMenuItem mnuOfD1;
    private javax.swing.JMenuItem mnuOfD2;
    private javax.swing.JMenuItem mnuOfD3;
    private javax.swing.JMenuItem mnuOfN1;
    private javax.swing.JMenuItem mnuOfN2;
    private javax.swing.JMenuItem mnuOfN3;
    private javax.swing.JMenuItem mnuPrincipales;
    private javax.swing.JMenuItem mnuPrincipales1;
    private javax.swing.JMenuItem mnuSalir;
    private javax.swing.JMenuItem mnuSecudarias;
    private javax.swing.JMenuItem mnuSecudarias1;
    private javax.swing.JMenuItem mnuSeguridad;
    private javax.swing.JMenuItem mnuSeguridad1;
    private javax.swing.JMenuItem mnuTodasD;
    private javax.swing.JMenuItem mnuTodasD1;
    private javax.swing.JMenuItem mnuTodasN;
    private javax.swing.JMenuItem mnuTodasN1;
    private javax.swing.JPanel pnOficina1;
    private javax.swing.JPanel pnOficina2;
    private javax.swing.JPanel pnOficina3;
    // End of variables declaration//GEN-END:variables
}
